insert into servers (server_id, url, user_id, port, local_dome_user, local_dome_user_password, dome_user_space)
	values (3, 'localhost', 111, 7795, 'ceed', 'ceed', 'USER'); 

insert into service (service_id, organization_id, title, owner_id, project_id)
	values (3,1,'Alpha service', 111, 1);
	
insert into service_interface (interface_id,version, model_id, interface_id_str, type, name, service_id, server_id)
	values (1,1, 'aff647da-d82f-1004-8e7b-5de38b2eeb0f', 'aff647db-d82f-1004-8e7b-5de38b2eeb0f', 'interface',
		'Default Interface', 3,3);

insert into service_interface_path values (1,30);
		
insert into service_specifications (id, service_id, input, output, special, usage_stats, run_stats) values (1, 3, 2, 1, '[]','null','null');

insert into service_interface_parameter (parameter_id, interface_id, name, type, unit, category, default_value, parameter_id_txt, parameter_position, input_parameter)
	values (1, 1, 'SpecimenWidth', 'Real', 'meter', 'length', 3, 'd9f30f3a-d800-1004-8f53-704dbfababa8', 1, true);
insert into service_interface_parameter (parameter_id, interface_id, name, type, unit, category, default_value, parameter_id_txt, parameter_position, input_parameter)
	values (2, 1, 'CrackLength', 'Real', 'meter', 'length', 1, 'd9f30f37-d800-1004-8f53-704dbfababa8', 2, true);
insert into service_interface_parameter (parameter_id, interface_id, name, type, unit, category, default_value, parameter_id_txt, parameter_position, input_parameter, instancename)
	values (3, 1, 'Alpha', 'Real', 'no unit', 'no unit', 0.3333333333333333, 'd9f30f3d-d800-1004-8f53-704dbfababa8', 3, false,'Alpha');
	
--
-- Data for Name: service_run; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY service_run (run_id, status, account_id, run_by, service_id, percent_complete, start_date, stop_date, interface_id, queue_name) FROM stdin;
1	1	550	550	3	50	2016-03-21	2016-03-22	1	queue
\.

SELECT pg_catalog.setval('service_run_id_seq', 1);
	
SELECT pg_catalog.setval('service_interface_parameter_id_seq', 3);
SELECT pg_catalog.setval('service_interface_interface_id_seq1', 3);
SELECT pg_catalog.setval('service_specifications_id_seq', 1);
SELECT pg_catalog.setval('service_service_id_seq', 3);



--
-- Data for Name: service_compare; Type: TABLE DATA; Schema: public; Owner: gforge
--

INSERT into service_compare (service_id, profile_id) values (1, 111);
INSERT into service_compare (service_id, profile_id) values (2, 111);
INSERT into service_compare (service_id, profile_id) values (3, 111);
