insert into community_event (title, on_date, start_time, end_time, address, description) values ('Breakfast', '10/18/2016', '8:00 am', '9:00 am', 'UILABS', 'Breakfast@UI');
insert into community_event (title, on_date, start_time, end_time, address, description) values ('Lunch', '10/31/2017', '12:00 pm', '1:00 pm', 'UILABS', 'Lunch@UI');
insert into community_event (title, on_date, start_time, end_time, address, description) values ('Dinner', '12/05/2018', '7:00 pm', '8:30 pm', 'UILABS', 'Dinner@UI');
