
--
-- Data for Name: artifact; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact (artifact_id, group_artifact_id, status_id, priority, submitted_by, assigned_to, open_date, close_date, summary, details, last_modified_date) FROM stdin;
\.


--
-- Data for Name: artifact_canned_responses; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_canned_responses (id, group_artifact_id, title, body) FROM stdin;
\.


--
-- Data for Name: artifact_counts_agg; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_counts_agg (group_artifact_id, count, open_count) FROM stdin;
100	0	0
\.


--
-- Data for Name: artifact_extra_field_data; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_extra_field_data (data_id, artifact_id, field_data, extra_field_id) FROM stdin;
\.


--
-- Data for Name: artifact_extra_field_elements; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_extra_field_elements (element_id, extra_field_id, element_name, status_id, element_pos) FROM stdin;
\.


--
-- Data for Name: artifact_extra_field_list; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_extra_field_list (extra_field_id, group_artifact_id, field_name, field_type, attribute1, attribute2, is_required, alias) FROM stdin;
\.


--
-- Data for Name: artifact_file; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_file (id, artifact_id, description, bin_data, filename, filesize, filetype, adddate, submitted_by) FROM stdin;
\.


--
-- Data for Name: artifact_group_list; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_group_list (group_id, name, description, is_public, allow_anon, email_all_updates, email_address, due_period, submit_instructions, browse_instructions, datatype, status_timeout, custom_status_field, custom_renderer, browse_list) FROM stdin;
1	Default	Default Data - Dont Edit	3	0	0		2592000	\N	\N	0	\N	0	\N	summary,open_date,assigned_to,submitted_by
\.


--
-- Data for Name: artifact_message; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_message (id, artifact_id, submitted_by, from_email, adddate, body) FROM stdin;
\.


--
-- Data for Name: artifact_monitor; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_monitor (id, artifact_id, user_id, email) FROM stdin;
\.

--
-- Data for Name: artifact_query; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_query (artifact_query_id, group_artifact_id, user_id, query_name, query_type, query_options) FROM stdin;
\.


--
-- Data for Name: artifact_query_fields; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_query_fields (artifact_query_id, query_field_type, query_field_id, query_field_values) FROM stdin;
\.


--
-- Data for Name: artifact_status; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_status (id, status_name) FROM stdin;
1	Open
2	Closed
\.


--
-- Data for Name: artifact_type_monitor; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_type_monitor (group_artifact_id, user_id) FROM stdin;
\.


--
-- Data for Name: artifact_workflow_event; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_workflow_event (event_id, group_artifact_id, field_id, from_value_id, to_value_id) FROM stdin;
\.

--
-- Data for Name: artifact_workflow_notify; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_workflow_notify (event_id, role_id) FROM stdin;
\.

--
-- Data for Name: artifact_workflow_roles; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY artifact_workflow_roles (event_id, role_id) FROM stdin;
\.


--
-- Name: artifact_artifact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_artifact_id_seq', 1, false);


--
-- Name: artifact_canned_response_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_canned_response_id_seq', 1, false);


--
-- Name: artifact_extra_field_data_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_extra_field_data_data_id_seq', 1, false);


--
-- Name: artifact_extra_field_elements_element_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_extra_field_elements_element_id_seq', 1, false);



--
-- Name: artifact_extra_field_list_extra_field_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_extra_field_list_extra_field_id_seq', 1, false);



--
-- Name: artifact_file_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_file_id_seq', 1, false);

--
-- Name: artifact_grou_group_artifac_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_grou_group_artifac_seq', 100, true);


--
-- Name: artifact_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_history_id_seq', 1, false);


--
-- Name: artifact_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_message_id_seq', 1, false);



--
-- Name: artifact_monitor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_monitor_id_seq', 1, false);



--
-- Name: artifact_query_artifact_query_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_query_artifact_query_id_seq', 1, false);

--
-- Name: artifact_status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_status_id_seq', 3, true);

--
-- Name: artifact_workflow_event_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('artifact_workflow_event_id_seq', 1, false);
