
INSERT INTO common_video_image_type VALUES (1, 'organization_video');
INSERT INTO common_video_image_type VALUES (2, 'organization_image');



--
-- Data for Name: canned_responses; Type: TABLE DATA; Schema: public; Owner: gforge
--

COPY canned_responses (response_id, response_title, response_text) FROM stdin;
\.

--
-- Name: canned_responses_pk_seq; Type: SEQUENCE SET; Schema: public; Owner: gforge
--

SELECT pg_catalog.setval('canned_responses_pk_seq', 1, false);
